pluginManagement {
    repositories {
        // BMCLAPI 国内镜像（完整镜像 maven.minecraftforge.net，下载 FG 插件与依赖）
        maven {
            name = 'BMCLAPI-MinecraftForge'
            url = 'https://bmclapi2.bangbang93.com/maven'
        }
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}